name: github pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: doxygen
              uses: mattnotmitt/doxygen-action@v1
              with:
                  working-directory: "docs/"
                  doxyfile-path: "Doxyfile"
