name: github pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Checkout submodules
              uses: textbook/git-checkout-submodule-action@master

            - name: Doxygen
              uses: mattnotmitt/doxygen-action@v1
