name: github pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Checkout submodules
              uses: textbook/git-checkout-submodule-action@master

            - name: Doxygen
              uses: mattnotmitt/doxygen-action@v1

            - name: Commit and Push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_USER: ${ GITHUB_ACTOR }
                  GITHUB_EMAIL: ${ GITHUB_ACTOR }@domain.io
                  GITHUB_REPOSITORY: ${ GITHUB_REPOSITORY }
              run: ./doxygen.sh
